#!/bin/bash

alias discord='flatpak run com.discordapp.Discord'
alias obs-studio='flatpak run com.obsproject.Studio'
alias spotify='flatpak run com.spotify.Client'
alias bottles='flatpak run com.usebottles.bottles'
alias bottles-cli='flatpak run --command=bottles-cli com.usebottles.bottles'
alias handbrake='flatpak run fr.handbrake.ghb'
alias freetube='flatpak run io.freetubeapp.FreeTube'
alias brisk='flatpak run io.github.BrisklyDev.Brisk'
alias joplin='flatpak run net.cozic.joplin_desktop'
alias chromium='flatpak run org.chromium.Chromium'
alias gimp='flatpak run org.gimp.GIMP'
alias aisleriot='flatpak run org.gnome.Aisleriot'
alias krita='flatpak run org.kde.krita'
alias musescore='flatpak run org.musescore.MuseScore'
alias onlyoffice='flatpak run org.onlyoffice.desktopeditors'
alias telegram='flatpak run org.telegram.desktop'
alias vlc='flatpak run org.videolan.VLC'
