name: install-tools-first-full
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        timeout-minutes: 360
        uses: actions/checkout@v4
      - name: Patch
        timeout-minutes: 360
        run: sed -i 's/sudo reboot/true/' install-tools-first.sh
      - name: Run install-tools-first.sh
        timeout-minutes: 360
        run: ./install-tools-first.sh
