name: install-tools-first
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu:24.04
          - ubuntu:26.04
          - ubuntu:rolling
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout repository
        timeout-minutes: 360
        uses: actions/checkout@v4
      - name: Run install-tools-first.sh
        timeout-minutes: 360
        run: |
          ./install-tools-first.sh --test
