name: install-tools-first-full
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    container:
      image: ubuntu:26.04
    steps:
      - name: Checkout repository
        timeout-minutes: 360
        uses: actions/checkout@v4
      - name: Run install-tools-first.sh
        timeout-minutes: 360
        run: |
          set -euxo pipefail
          useradd -m runner
          chown -R runner:runner "$GITHUB_WORKSPACE"
          usermod -aG sudo runner
          mkdir -p /etc/sudoers.d
          echo 'runner ALL=(ALL) NOPASSWD:ALL' >/etc/sudoers.d/runner
          chmod 440 /etc/sudoers.d/runner
          apt update
          DEBIAN_FRONTEND=noninteractive apt install sudo -y
          su - runner <<'88837a96-9ded-412a-81c4-eff9b1ef1822'
          set -euxo pipefail
          FIRSTDF=$(df --output=used / | tail -n1)
          sudo DEBIAN_FRONTEND=noninteractive apt install kubuntu-desktop -y
          sudo apt clean
          ./install-tools-first.sh --full
          echo "FIRSTDF: $FIRSTDF"
          88837a96-9ded-412a-81c4-eff9b1ef1822
