name: install-tools-first
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-26.04
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        timeout-minutes: 360
        uses: actions/checkout@v4
      - name: Run install-tools-first.sh
        timeout-minutes: 360
        run: ./install-tools-first.sh --test
