name: Test install-tools-first

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Patch script
        run: |
          export x="$(echo "$(cat << d23fac94-9e7a-47b0-92e9-ac5a8a7c7a41
          wget --tries=100 --retry-connrefused --waitretry=5 https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          rm install-tl-unx.tar.gz
          cd install-tl-*
          sudo perl ./install-tl --no-interaction
          cd ~
          rm -rf install-tl-*
          sudo /usr/local/texlive/2026/bin/x86_64-linux/tlmgr update --all --self --reinstall-forcibly-removed
          mkdir -p ~/.config/fontconfig/conf.d
          cat > ~/.config/fontconfig/conf.d/99-texlive.conf <<'EOF'
          <?xml version="1.0"?>
          <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
          <fontconfig>
            <dir>/usr/local/texlive/2026/texmf-dist/fonts</dir>
          </fontconfig>
          EOF
          sudo fc-cache -fv
          cd /usr/share
          sudo git clone https://github.com/Willie169/LaTeX-ToolKit
          cd ~
          mkdir -p texmf
          cd texmf
          mkdir -p tex
          cd tex
          mkdir -p latex
          cd latex
          git clone https://github.com/Willie169/physics-patch
          cd physics-patch
          git checkout dev
          cd ~

          d23fac94-9e7a-47b0-92e9-ac5a8a7c7a41
          )")"
          perl -0777 -i -pe '
          my $pat = $ENV{x};
          $pat =~ s/\r\n/\n/g;
          my @lines = split /\n/, $pat;
          my $re = join "\\R", map { quotemeta($_) } @lines;
          s/$re//g;
          s/wget --tries=100 --retry-connrefused --waitretry=5 https:\/\/edgedl\.me\.gvt1\.com\/android\/studio\/ide-zips.*sudo rm \/bin\/sdkmanager 2>\/dev\/null \|\| true//s;
          s/export KICAD_VERSION.*Icon=\$HOME\/\.local\/kicad\/icon_kicad\.ico\nTerminal=false\nCategories=Development;\nEOF//s;
          ' -- install-tools-first.sh
          perl -i -pe '
          s/^npm i\b(.*)/npm i$1 --dry-run/;
          s/^brew install\b(.*)/brew install$1 --dry-run/;
          s/^deb-get install.*//;
          s/^sudo flatpak.*//;
          s/^sudo fc-cache -fv//;
          s/^sudo reboot//;
          s/^[ \t]*fcitx5 &//;
          s/^echo y \| sudo ubuntu-drivers [a-z]+ \|\| true//;
          s/^sudo apt install (brave-browser|rustdesk rustdesk-server|lazygit|eza|gitcomet|element-desktop) -y/sudo apt install $1 -y --dry-run/;
          BEGIN { $seen = 0; $count = 0 }
          if (!$seen && /sudo apt upgrade -y/) {
            $seen = 1;
            $count = 3;
          }
          if ($seen && $count > 0) {
            if ($count < 3) {
              s/$/ --dry-run/;
            }
            $count--;
            if ($count == 0) {
                $_ .= "sudo apt install apparmor-utils apt-transport-https build-essential ca-certificates clamav clamav-daemon cmake curl dbus debian-archive-keyring debian-keyring default-jdk dnscrypt-proxy gcc git gpg g++ make maven ninja-build perl python-is-python3 python3 python3-pip python3-venv wget -y\n";
            }
          }
          ' -- install-tools-first.sh

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install ubuntu-desktop-minimal -y

      - name: Run install-tools-first.sh
        run: |
          ./install-tools-first.sh 2>&1 | tee install-tools-first.log

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: install-tools-first.log
          path: install-tools-first.log
