name: Test install-tools-first

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Patch script
        run: |
          sudo apt update
          sudo apt install perl -y
          export x="$(echo "$(cat << d23fac94-9e7a-47b0-92e9-ac5a8a7c7a41
          wget --tries=100 --retry-connrefused --waitretry=5 https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          rm install-tl-unx.tar.gz
          cd install-tl-*
          sudo perl ./install-tl --no-interaction
          cd ~
          rm -rf install-tl-*
          sudo /usr/local/texlive/2026/bin/x86_64-linux/tlmgr update --all --self --reinstall-forcibly-removed
          mkdir -p ~/.config/fontconfig/conf.d
          cat > ~/.config/fontconfig/conf.d/99-texlive.conf <<'EOF'
          <?xml version="1.0"?>
          <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
          <fontconfig>
            <dir>/usr/local/texlive/2026/texmf-dist/fonts</dir>
          </fontconfig>
          EOF
          sudo fc-cache -fv
          cd /usr/share
          sudo git clone https://github.com/Willie169/LaTeX-ToolKit
          cd ~
          mkdir -p texmf
          cd texmf
          mkdir -p tex
          cd tex
          mkdir -p latex
          cd latex
          git clone https://github.com/Willie169/physics-patch
          cd physics-patch
          git checkout dev
          cd ~

          d23fac94-9e7a-47b0-92e9-ac5a8a7c7a41
          )")"
          perl -0777 -i -pe '
            my $pat = $ENV{x};
            $pat =~ s/\r\n/\n/g;
            my @lines = split /\n/, $pat;
            my $re = join "\\R", map { quotemeta($_) } @lines;
            s/$re//g;
          ' -- install-tools-first.sh
          perl -0777 -i -pe 's/sudo reboot//;' -- install-tools-first.sh

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install ubuntu-desktop-minimal -y

      - name: Run install-tools-first.sh
        run: |
          ./install-tools-first.sh 2>&1 | tee install-tools-first.log

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: install-tools-first.log
          path: install-tools-first.log
