name: test
on:
  workflow_dispatch:
jobs:
  install:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    container:
      image: ubuntu:26.04
    steps:
      - name: Prepare Kubuntu
        timeout-minutes: 360
        run: |
          set -euxo pipefail
          useradd -m runner
          chown -R runner:runner "$GITHUB_WORKSPACE"
          usermod -aG sudo runner
          echo 'runner ALL=(ALL) NOPASSWD:ALL' >/etc/sudoers.d/runner
          chmod 440 /etc/sudoers.d/runner
          apt update
          DEBIAN_FRONTEND=noninteractive apt install sudo -y
          su - runner <<'88837a96-9ded-412a-81c4-eff9b1ef1822'
          df --output=used / | tail -n1
          sudo apt list --manual-installed 2>/dev/null | sed 's/\/.*//; /\.\.\./d' | xargs sudo apt-mark auto
          sudo DEBIAN_FRONTEND=noninteractive apt install kubuntu-desktop -y
          sudo apt autoremove -y
          sudo apt clean
          df --output=used / | tail -n1
          88837a96-9ded-412a-81c4-eff9b1ef1822
